services:
  - type: web
    name: financasalao
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 4 --timeout 120
    envVars:
      - key: DB_URL
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: SECURITY_SALT
        sync: false
      - key: SUPPORT_PHONE
        sync: false
      - key: RENDER_BASE_URL
        sync: false
      - key: COOKIE_SECURE
        value: "true"
